stages:
  - publish

publish_to_jsr:
  image: oven/bun # Uses Bun's official image
  stage: publish
  only:
    - main # Runs only on the main branch
  script:
    - bunx jsr publish --token "$JSR_AUTH_TOKEN"
  after_script:
    - echo "Package successfully published to JSR!"
